// components/BlogpostItem/BlogpostItem.jsx
import { useEffect, useState } from 'react';
import Link from 'next/link'
import useFormatDate from '@hooks/useFormatDate.js';
import BlogpostItemStyles from './BlogpostItemStyles';

export default function BlogpostItem({ post }) {
  const formatDate = useFormatDate();
  const [formattedDate, setFormattedDate] = useState("");

  useEffect(() => {
    const formattedDate = formatDate(post.created_at, navigator.language)
    setFormattedDate(formattedDate);
  }, [formatDate, post.created_at]);

  return (
    <>
      <div className="blogpost-item">
        <Link href={post.state ? `/blog/${post.slug}` : '#'}>
          <a className="blogpost-item__link">
            <div className="blogpost-item__heading">
              <span className="blogpost-item__date">
                {post.state ? formattedDate : "Coming soon"}
              </span>
              <span
                className={`blogpost-item__reading-time${!post.state ? ' blogpost-item__reading-time--opaque' : ''}`}
              >
                {post.read_time} min read
              </span>
            </div>
            <div className={`blogpost-item__title${!post.state ? ' blogpost-item__title--opaque' : ''}`}>
              <p className="text-2xl text-black font-bold hover:underline">
                {post.title}
              </p>
              <p className="blogpost-item__description">
                {post.description}
              </p>
            </div>
          </a>
        </Link>
      </div>

      <style jsx>
        {BlogpostItemStyles}
      </style>
    </>
  );
}

// components/BlogpostItem.vue
<template>
  <div class="mt-6">
    <NuxtLink
      :to="post.state ? `/blog/${post.slug}` : '#'"
      class="block max-w-2xl px-5 md:px-9 py-6 mx-auto bg-white rounded-lg shadow-md cursor-pointer"
    >
      <div class="flex justify-between items-center">
        <span class="text-sm text-blue-700 font-light">
          {{ post.state ? formattedDate : "Coming soon" }}
        </span>
        <span
          :class="{ 'opacity-50': !post.state }"
          class="text-sm text-black font-light"
        >
          {{ post.read_time }} min read
        </span>
      </div>
      <div :class="{ 'opacity-50': !post.state }" class="mt-2 mb-1">
        <p class="text-2xl text-black font-bold hover:underline">
          {{ post.title }}
        </p>
        <p class="mt-2 text-black">
          {{ post.description }}
        </p>
      </div>
    </NuxtLink>
  </div>
</template>

<script>
import { dateFormatMixin } from "../mixins/dateFormatMixin";

export default {
  name: "BlogpostItem",
  mixins: [dateFormatMixin],
  props: ["post"],
  data() {
    return {
      formattedDate: this.formatDate(this.post.created_at),
    };
  },
  beforeMount() {
    this.formattedDate = this.formatDate(
      this.post.created_at,
      navigator.language
    );
  },
};
</script>

<style>
</style>
